apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: alpine-v1
  labels: &labels
    app: alpine
    version: v1
spec:
  replicas: 1
  selector:
    <<: *labels
  template:
    metadata:
      creationTimestamp: null
      labels:
        <<: *labels
    spec:
      containers:
        - image: workstation:v1
          name: workstation
          volumeMounts:
          - mountPath: /home/mr
            name: home
          - mountPath: /etc/dropbear
            name: dropbear-keys
          ports:
            - containerPort: 22
          livenessProbe:
            tcpSocket:
              port: 22
      volumes:
        - name: home
          hostPath: 
            path: /home/mr
        - name: dropbear-keys
          secret:
            secretName: workstation-ssh-host-keys
