apiVersion: v1
kind: ReplicationController
metadata:
  name: scherbengericht-v1
  labels: &labels
    app: scherbengericht
    version: v1
spec:
  replicas: 1
  selector:
    <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      containers:
      - image: matthiasr/scherbengericht
        name: scherbengericht
