apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-lb-v1
  labels: &labels
    app: nginx-lb
    version: v1
spec:
  replicas: 2
  selector:
    <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      containers:
      - image: matthiasr/nginx-lb
        name: web
        ports:
        - containerPort: 80
        - containerPort: 443
        livenessProbe:
          httpGet:
            port: 80
        volumeMounts:
        - mountPath: /etc/nginx/secrets
          name: keys
      volumes:
      - name: keys
        secret:
          secretName: nginx-lb-keys
