apiVersion: v1
kind: ReplicationController
metadata:
  name: workstation-v2
  labels: &labels
    app: workstation
    version: v2
spec:
  replicas: 1
  selector:
    <<: *labels
  template:
    metadata:
      creationTimestamp: null
      labels:
        <<: *labels
    spec:
      containers:
        - image: workstation:v2
          name: workstation
          volumeMounts:
          - mountPath: /home/mr
            name: home
          - mountPath: /etc/ssh/keys
            name: openssh-keys
          ports:
            - containerPort: 22
          livenessProbe:
            tcpSocket:
              port: 22
      volumes:
        - name: home
          hostPath: 
            path: /home/mr
        - name: openssh-keys
          secret:
            secretName: workstation-openssh-host-keys
