apiVersion: v1
kind: ReplicationController
metadata:
  name: logformat-bot-v1
  labels: &labels
    app: logformat
    proc: bot
    version: v1
spec:
  replicas: 1
  selector:
    <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      containers:
      - image: matthiasr/logformat:latest
        name: bot
        command:
        - bin/run
        - bot.rb
        env:
        - name: DB
          value: postgres://logformat:changeme@postgres.default.svc.k.2pktfkt.net:5432/postgres?sslmode=disable&encoding=utf-8
        - name: NICK
          value: kubformat
