apiVersion: v1
kind: ReplicationController
metadata:
  name: logformat-web-v1
  labels: &labels
    app: logformat
    proc: web
    version: v1
spec:
  replicas: 2
  selector:
    <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      containers:
      - image: matthiasr/logformat:latest
        name: web
        ports:
        - containerPort: 8080
        livenessProbe:
          initialDelaySeconds: 30
          httpGet:
            port: 8080
        env:
        - name: DB
          value: postgres://logformat:changeme@postgres.default.svc.k.2pktfkt.net:5432/postgres?sslmode=disable&encoding=utf-8
