apiVersion: v1beta3
kind: ReplicationController
metadata:
  name: prometheus-v2
  labels: &labels
    app: prometheus
    version: v2
spec:
  replicas: 1
  selector:
    <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      containers:
        - name: prometheus
          image: matthiasr/prometheus:glibc
          volumeMounts:
          - name: prometheus-storage
            mountPath: /prometheus
          ports:
            - containerPort: 9090
          livenessProbe:
            httpGet:
              port: 9090
      volumes:
        - name: prometheus-storage
          hostPath:
            path: /srv/kubernetes/data/prometheus
