apiVersion: v1
kind: ReplicationController
metadata:
  name: prometheus-v3
  labels: &labels
    app: prometheus
    version: v3
spec:
  replicas: 1
  selector:
    <<: *labels
  template:
    metadata:
      labels:
        <<: *labels
    spec:
      containers:
        - name: prometheus
          image: matthiasr/prometheus:latest
          volumeMounts:
          - name: prometheus-storage
            mountPath: /prometheus
          ports:
            - containerPort: 9090
          livenessProbe:
            httpGet:
              port: 9090
        - name: kubectl
          image: matthiasr/kubectl:1.0.1
          args:
            - proxy
            - -p
            - "8001"
            - --api-prefix=/
      volumes:
        - name: prometheus-storage
          hostPath:
            path: /srv/kubernetes/data/prometheus
