#!/bin/sh

exec 2>&1

. /srv/kubernetes/etc/base.conf

exec "${BASE}/bin/etcd" --data-dir="${ETCD_DATA_DIR}" --listen-client-urls="${ETCD_URL}" --advertise-client-urls="${ETCD_URL}" --listen-peer-urls="${ETCD_PEER_URL}"
